### ISSUE TITLE
Safari unable to use in private mode

### ISSUE THREAD

**Issue by neviaumi** [aws/aws-sdk-mobile-analytics-js#10]
While safari running on private mode window.localStorage will be available (not null/undefined ) but setItem will throw exception . It will make data loss while user this library to tracking . 

Currently my solution is create custom in-memory storage to replace default storage while below condition is fulfilled : 

testStorageAvailable=()->
    storage = window.localStorage
    if storage?
        try
            storage.setItem("Storage Available", "true")
            return true
        catch e
            return false
    else
        return false

**Comment by cheruvian** [comment]
This should be resolved in v0.9.1
