### ISSUE TITLE
Add possibility to configure region specific for mobile analytics

### ISSUE THREAD

**Issue by MattiasLindskog** [aws/aws-sdk-mobile-analytics-js#11]
We use the eu-west-1 region when possible. Since mobile analytics is only available in us-east-1 it would be great to have a possibility to configure the region when setting up a new manager instead of having to use AWS.config.region.

**Comment by cheruvian** [comment]
With release 0.9.1 you can now pass options like region directly to the low level client via the [clientOptions configuration](https://aws.github.io/aws-sdk-mobile-analytics-js/doc/AMA.Client.html#Options).

`
new AMA.Manager({
    appId: APPLICATION_ID,
    clientOptions: {
        region: 'us-east-1',
    }
})
`
