### ISSUE TITLE
Custom events do not appear in "Custom Events" dashboard

### ISSUE THREAD

**Issue by kest85** [aws/aws-sdk-mobile-analytics-js#13]
I have integrated everything as described (including call recordEvent()), but custom events do not appear in "Custom Events" dashboard. No errors in console. Also, I have tried many diffrerent variations, like setting endpoint manually, using startSession(), createEvent() functions, but I have not found combination which would work. Does custom events functionality work with js for anyone?

**Comment by Graphfx** [comment]
I have exactly the same problem...

**Comment by cheruvian** [comment]
We're happy to see if there is an issue with the JS SDK, some quick questions to help us determine the issue:
1.Which version of this repo are you using? (0.9.0 or 0.9.1)
2.Which version of the AWS SDK are you using? (Please note Mobile Analytics was not added until v2.1.18 though newer improvements depend on v2.2.37)
3.Which client are you using AMA.Manager or AMA.Client?
4.Is this integration intended for desktop browsers, mobile browsers, web views or HTML5 apps (cordova, phonegap, etc...)?
5.Finally, are you able to verify if requests are being made to the Amazon Mobile Analytics Service (please note the response code, 202 or 4XX)?

Please note that you can always reach out to us directly at amazon-mobile-analytics@amazon.com (Please include AWS Account ID and AMA Application ID) or post in the[ AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=174&start=0) (_do not_ post your AWS Account ID to the forums, AWS Support can retrieve this information from your login).

**Comment by kest85** [comment]
1. 0.9.0
2. v2.2.33
3. AMA.Manager
4. Ionic app (cordova)
5. I don't see any responses output in console. Is there a way to enable it?

I can see users and sessions in aws dashboard, but no custom events and no monetization events.

**Comment by Graphfx** [comment]
You can enable the output messages by adding a logger has option of `AMA.Manager`.

`
... new AMA.Manager({
            appId : _APP_ID,
            ...
            logger: console
        };
`

Personally I have "_Events Submitted Successfully_" and status code 202 (but nothing on the AWS dashboard).

**Comment by cheruvian** [comment]
As @Graphfx has mentioned, you can pass a logger object as part of your initalization options.  The full list of parameters can be [found in the docs here](https://aws.github.io/aws-sdk-mobile-analytics-js/doc/AMA.Client.html#Options).

Please go ahead and engage us via email at amazon-mobile-analytics@amazon.com (Please include AWS Account ID and AMA Application ID) or post in the[ AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=174&start=0) (_do not_ post your AWS Account ID to the forums, AWS Support can retrieve this information from your login) so that we can dive into this discrepancy further.

**Comment by kest85** [comment]
This is the reason, why my events have failed:
"Event Metric and Attribute Count cannot exceed 40"

Are there any plans to support higher number of metrics/atributes in future?

**Comment by stevmachine** [comment]
I have the same problem. But in my case i try with console logger, and looks like all normal:

![image](https://cloud.githubusercontent.com/assets/17983441/14655425/a2fcca68-0658-11e6-9669-c4e6c4738451.png)

![image](https://cloud.githubusercontent.com/assets/17983441/14655405/8c3e734e-0658-11e6-90d7-59c631807e1e.png)


1.- 0.9.1
2.- v2.3.3
3.- AMA.Manager
4.- Ionic app v.1.7.14 (cordova v.5.4.1)
5.- I obtain 202 

![image](https://cloud.githubusercontent.com/assets/17983441/14655333/2bda0ebe-0658-11e6-8225-3c8747bbd2c5.png)

**Comment by mdinescu** [comment]
Hi @kest85,

I apologize for the long delay getting back to you on your question about increasing the limits of our service (http://docs.aws.amazon.com/mobileanalytics/latest/ug/limits.html).

Unfortunately we can't make any comments about our plans or feature road-maps here, however we're always interested in learning more about our customer's use cases and ways in which you would like to use our products. 

If you'd like to discuss your use case for high-number of metrics and/or attributes please don't hesitate to engage us via email at amazon-mobile-analytics@amazon.com, or post in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=174&start=0) (_do NOT_ post your AWS Account ID to the forums - AWS Support can retrieve this information from your login).
