### ISSUE TITLE
Change to Local Storage key could result in bad tracking when updating to latest version of the library

### ISSUE THREAD

**Issue by eanticev** [aws/aws-sdk-mobile-analytics-js#15]
Here: https://github.com/aws/aws-sdk-mobile-analytics-js/commit/c672a41e7fad3fc691e6b1592b8212e0cbf6d1ec#diff-9f59baab3debe03b94bd38548e5cf841R16 you've changed the local storage key.

Anyone updating from an old version to this version of the library to show completely incorrect data in the dashboard since every device will be counted as a new device.

**Comment by cheruvian** [comment]
This issue has been resolved in v0.9.2

I'll go ahead and throw up a warning on the v0.9.1 README
