### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by nitrag** [aws/aws-sdk-mobile-analytics-js#16]
How are you supposed to compile?

`npm install`
`npm install --dev` <-- a ton of errors
`bower install`
what am I missing?

`grunt`

**Comment by cheruvian** [comment]
The library is prebuilt and available for use, it can be found at `dist/aws-sdk-mobile-analytics.min.js`

To build it yourself simply run `npm install` and it will compile and minify to the `dist` location.
