### ISSUE TITLE
Refactor and streamline grunt tasks?

### ISSUE THREAD

**Issue by TDA** [aws/aws-sdk-mobile-analytics-js#17]
Currently, we have all our tasks loaded in a hardcoded way, and moving our tasks to separate files inside a folder like `grunt-tasks` will not only allow more control over the individual tasks, but also allow us to load all the tasks without explicitly hardcoding them.

Willing to put in a PR if this idea sounds good.
@isuttle 
@cheruvian

**Comment by cheruvian** [comment]
Sounds reasonable, I'm happy to look over any PR you submit.
