### ISSUE TITLE
Direct Console Object Usage

### ISSUE THREAD

**Issue by summraznboi** [aws/aws-sdk-mobile-analytics-js#2]
In LocalStorage.js file, there are console.log usages, which can be unsafe since console isn't covered by any formal specifications. Also, it prevents me from retrieving these logs by using my own logger function. Pull request can be seen at https://github.com/aws/aws-sdk-mobile-analytics-js/pull/1.

Thanks,
Steven Lee

**Comment by cheruvian** [comment]
The pull request has been reviewed, approved and merged.

Thank you for your contribution.
