### ISSUE TITLE
No internet connection mode not working

### ISSUE THREAD

**Issue by fkindy01** [aws/aws-sdk-mobile-analytics-js#21]
Hello everyone i have follow the exact steps and works fine when my app is connected to the WiFi but the below error is triggered when i use my app with no internet connection

Failed to load resource: net::ERR_NAME_NOT_RESOLVED    https://undefined.us-east-1.amazonaws.com/ 

Isn't there automatically suppose to local storage the events and when is online to send it or should i make it? Cause in android and ios native language AWS automatically take care of this issues.

Thanx in advance!

**Comment by johnborges** [comment]
Can you post some sample code on how you're instantiating the `AMA.Manager`. The URL you're trying to hit looks wrong.

**Comment by richabra** [comment]
How have you brought in the aws sdk? Is it local or remote (<script src="https://sdk.amazonaws.com/js/aws-sdk-2.4.12.min.js"></script>)?

**Comment by fkindy01** [comment]
Thanks for all the help guys. I have fixed the issue! it was a problem with the way i handle the data
