### ISSUE TITLE
Is this working with react-native apps?

### ISSUE THREAD

**Issue by peterleilei86** [aws/aws-sdk-mobile-analytics-js#24]
Can I use this library in a react-native app to collect user data?

**Comment by rcha** [comment]
We have no official support for react-native, but you may try to use it. Feel free to send Pull-Requests as well. Thanks

**Comment by spoeck** [comment]
I made a demo for using it with React-Native:
https://github.com/spoeck/react-native-aws-mobile-analytics-demo

**Comment by spoeck** [comment]
I made a version for using it with React-Native and AsyncStore support:
https://github.com/innFactory/react-native-aws-mobile-analytics
`npm i --save react-native-aws-mobile-analytics`
