### ISSUE TITLE
Not working inside service worker . 

### ISSUE THREAD

**Issue by sk16** [aws/aws-sdk-mobile-analytics-js#26]
Mobile analytics is not working inside service worker . Its not sending any session-start , session-stop or any custom event .

**Comment by cheruvian** [comment]
[Amazon Mobile Analytics is now Amazon Pinpoint](https://aws.amazon.com/blogs/mobile/mobile-analytics-is-moving-to-amazon-pinpoint/).  The official recommended SDK for recording events to Amazon Pinpoint in javascript is [AWS Amplify](https://github.com/aws/aws-amplify) which does work within a service worker.
