### ISSUE TITLE
Remove dependency from aws-sdk

### ISSUE THREAD

**Issue by summraznboi** [aws/aws-sdk-mobile-analytics-js#4]
The aws-sdk.min.js file is roughly 200kb, seems overkill to need to include that for a 20kb library that only uses aws-sdk for authentication related stuff.

**Comment by cheruvian** [comment]
Currently all Auth, Signing and Service communication is handled by the aws-sdk-js library.

I recommend you open an issue in the aws-sdk-js repository requesting the ability to selectively build which Services/SDKs you want for a final minimized and distributable aws-sdk-js version.

Closing the issue.
