### ISSUE TITLE
Any plans to publish this to NPM?

### ISSUE THREAD

**Issue by mac-** [aws/aws-sdk-mobile-analytics-js#5]
It would be useful for those of us using browserify to build our JS bundles to be able to pull this in via NPM. Any thoughts?

**Comment by cheruvian** [comment]
You should now be able to require this in your `package.json` file:

<pre>
"dependencies": {
    "aws-sdk-mobile-analytics": ">=0.9.0",
    "aws-sdk": ">=2.1.18"
  }
</pre>

**Comment by mac-** [comment]
:+1:

**Comment by peterleilei86** [comment]
how do you use "aws-sdk-mobile-analytics" dependency in a react-native app? I can't import it from node module.
